# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (5)
# #########################################################################

class ClassificationResponse(BaseModel):
    model_reasoning: str
    chosen_theme: "Theme"

class ContactInfo(BaseModel):
    email: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    preferred_contact_method: typing.Optional[typing.Union[typing_extensions.Literal['Email'], typing_extensions.Literal['Phone']]] = None
    call_reasons: typing.Optional[typing.List[str]] = None

class FormCompletionResponse(BaseModel):
    personal_info: "PersonalInfo"
    contact_info: "ContactInfo"

class PersonalInfo(BaseModel):
    first_name: typing.Optional[str] = None
    last_name: typing.Optional[str] = None
    gender: typing.Optional[typing.Union[typing_extensions.Literal['Male'], typing_extensions.Literal['Female'], typing_extensions.Literal['Other']]] = None

class Theme(BaseModel):
    title: str
    description: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
